//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class company
{
	public virtual object company_id
	{
		get;
		set;
	}

	public virtual object contact_id
	{
		get;
		set;
	}

	public virtual object vat_registered
	{
		get;
		set;
	}

	public virtual object vat_number
	{
		get;
		set;
	}

	public virtual object company_name
	{
		get;
		set;
	}

	public virtual object address_id
	{
		get;
		set;
	}

}

